export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  STAFF: '/staff',
  STAFF_DETAIL: '/staff/:id',
  STAFF_EDIT: '/staff/:id/edit',
  STAFF_REQUESTS: '/staff-requests',
  SHIFTS: '/shifts',
  SHIFTS_CREATE: '/shifts/create',
  SHIFTS_DETAIL: '/shifts/:id',
  SHIFTS_EDIT: '/shifts/:id/edit',
  ATTENDANCE: '/attendance',
  DOCUMENTS: '/documents',
  COMPLIANCE: '/compliance',
  ADMIN_USERS: '/admin-users',
  ROLES_PERMISSIONS: '/roles-permissions',
  PERMISSIONS: '/permissions',
  AUDIT_LOGS: '/audit-logs',
  ANNOUNCEMENTS: '/announcements',
  NOTIFICATIONS: '/notifications',
  CUSTOMER: '/customer',
  CUSTOMER_SUPPORT: '/customer-support',
  SETTINGS: '/settings',
};
